// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  list_of_images: dynamic(() => import("./ListOfImages")),
  single_image: dynamic(() => import("./SingleImage")),
};
