// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  benefits: dynamic(() => import("./Benefits")),
  carbon_calculator_banner: dynamic(() => import("./CarbonCalculatorBanner")),
  click_to_action_banner: dynamic(() => import("./ClickToActionBanner")),
  community_logos: dynamic(() => import("./CommunityLogos")),
  hero: dynamic(() => import("./Hero")),
  hero_blog_version: dynamic(() => import("./HeroBlogPostVersion")),
  hero_go_neutral_version: dynamic(() => import("./HeroGoNeutralVersion")),
  hero_manage_plan_version: dynamic(() => import("./HeroManagePlanVersion")),
  hero_member_detail_version: dynamic(
    () => import("./HeroMemberDetailVersion"),
  ),
  hero_simple_version: dynamic(() => import("./HeroSimpleVersion")),
  hero_with_featured_blog_post_version: dynamic(
    () => import("./HeroWithFeaturedBlogPostVersion"),
  ),
  how_it_works: dynamic(() => import("./HowItWorks")),
  image: dynamic(() => import("./Image")),
  image_carousel: dynamic(() => import("./ImageCarousel")),
  information_banner: dynamic(() => import("./InformationBanner")),
  latest_three_stories: dynamic(() => import("./LatestThreeStories")),
  project_details_hero: dynamic(
    () => import("./HeroWithLogosInDarkSectionVersion"),
  ),
  projects_funded: dynamic(() => import("./ProjectsFunded")),
  projects_on_tabs: dynamic(() => import("./ProjectsOnTabs")),
  quote: dynamic(() => import("./Quote")),
  stats_with_text_panel: dynamic(() => import("./StatsWithTextPanel")),
  table: dynamic(() => import("./Table")),
  text: dynamic(() => import("./MarkdownText")),
  text_with_image: dynamic(() => import("./TextWithImage")),
  text_with_image_red_version: dynamic(
    () => import("./TextWithImageBulkyVersion"),
  ),
  text_with_padded_image: dynamic(() => import("./TextWithPaddedImage")),
};
